merge --all, first part
duqtools/duqtools pull request #435
Opened 2022-11-23 13:10 UTC by v1kko

2022-11-24 13:22 UTC, stefsmeets requested changes
Nice work, took me a while to review this PR, it does a lot 😅

I left some comments in the code where I felt that it was not entirely clear to me what is happening.

This PR will break the dashboard. Because the api for `merge_data` changes, the dashboard should be updated too.

Just a thought: `duqtools merge` enters new terrain by mixing values from `duqtools.yaml` with cli parameters. `-all` overrides what is defined in the config. I'm just wondering if this mixed interface is something that we want, or is this confusing? Should we allow variables to merge to be defined on the CLI as well?

2022-11-24 14:00 UTC, v1kko commented
> Nice work, took me a while to review this PR, it does a lot sweat_smile
> 
> I left some comments in the code where I felt that it was not entirely clear to me what is happening.
> 
> This PR will break the dashboard. Because the api for `merge_data` changes, the dashboard should be updated too.
> 
> Just a thought: `duqtools merge` enters new terrain by mixing values from `duqtools.yaml` with cli parameters. `-all` overrides what is defined in the config. I'm just wondering if this mixed interface is something that we want, or is this confusing? Should we allow variables to merge to be defined on the CLI as well?

Yes, actually it would make sense to define `merge` more like the `plot` command that we already have. And we could remove the `merge:` section from the config entirely. In that way we unify the API for merge (also for the dashboard) again, and there are less surprises

2022-11-24 14:03 UTC, v1kko commented on src/duqtools/ids/_merge.py
> +                variable_dict[name] = variables[-1]
1. its not _that_ unreadable, but that's subjective :smiley:
2. I agree, I will see if it can be hidden elsewhere

2022-11-24 14:16 UTC, stefsmeets commented
> Yes, actually it would make sense to define `merge` more like the `plot` command that we already have. And we could remove the `merge:` section from the config entirely. In that way we unify the API for merge (also for the dashboard) again, and there are less surprises

I think it's also helpful with #432 to do merging for large scale validation.

2022-11-24 14:52 UTC, stefsmeets commented on src/duqtools/ids/_merge.py
> +                variable_dict[name] = variables[-1]
re: 2

> Perhaps we should even have a var_lookup class that can deal with these cases and transparently pick up $rho_tor_norm and rho_tor_norm as the same variable.

This ties in with what I'm doing for #418 already, so I can take care of that part.

2022-11-24 15:57 UTC, v1kko commented on src/duqtools/ids/_mapping.py
> +    def write_back(self, variable: str, data: xr.DataArray) -> None:
You are correct that it is the inverse of _fill_array_from_parts, but its only 7 lines of code, and sufficiently distinct (and hard to merge a fetch and writeback operation) to leave it two separate functions.

2022-11-25 08:33 UTC, v1kko commented on src/duqtools/merge.py
> +        variables = list(variables)
yes

2022-11-25 08:34 UTC, v1kko commented on src/duqtools/ids/_merge.py
> +                variable_dict[name] = variables[-1]
I will leave this until #418 is ready

2022-11-25 08:38 UTC, v1kko commented on src/duqtools/ids/_merge.py
> +                                  std_data[name])
Correct, well, coincidentally this is how the data is stored in HDF5, and would be much faster, but I don't think that the IMAS Access Layer supports this type of variable access yet, unfortunately. If it becomes a bottleneck, we can look at it again

2022-11-25 08:45 UTC, v1kko commented on src/duqtools/ids/_merge.py
> +        idss = [handle.get(ids_name) for handle in handles]  # type: ignore
Yes good one

2022-11-25 09:07 UTC, v1kko commented
@stefsmeets I think everything that can/should be done later is in issues now, so lets merge this?

2022-11-25 09:19 UTC, merged